### ISSUE TITLE
Phase 1 - Projects

### ISSUE THREAD

**Issue by paulcox24** [devpointlabs/ProjectLab_Spring2015#1]
## Complete the following for Phase1
- [x] Read and follow this Guideline https://github.com/styleguide/ruby
- [x] Create a Project model 
`Project name description:text due_date:datetime`
- [x] Create Project controller and CRUD(create read update destroy) actions/views. Along with index and show actions/views
- [x] Add tests for the Project controller and model
- [x] Create a root page
- [x] Create a pull request for your changes.

### Phase1.1
Test the Project model
- [x] Validate the due date is later than today
- [x] Validate presence of name and description

Test the Project Controller
- [x] Test that creating a project adds 1 to Project.count
- [x] Test that editing a project actually works
- [x] Test that deleting a project removes 1 from Project.count

Add a StaticPages controller
- [x] Should have home, about, and contact

Create a Navbar
- [x] Should have links to home, about, contact, and projects index

## Remember
* Fork this repo
* Clone from your forked repo
* Set this repo as your upstream
* Do your work on a branch
* Push that branch to your forked repo
* Create a pull request of that branch

**Comment by QuintinAdam** [comment]
You should add https://houndci.com/ to these types of apps. It will leave comments on the PR's commits if there are style violations.
